Update robot-workflow-org.yml

diff --git a/.github/workflows/robot-workflow-org.yml b/.github/workflows/robot-workflow-org.yml
--- a/.github/workflows/robot-workflow-org.yml
+++ b/.github/workflows/robot-workflow-org.yml
@@ -39,3 +39,9 @@ jobs:
       with:
         name: robot-reports-run-${{ github.run_number }}
         path: reports/run_${{ github.run_number }}
+
+    - name: Fail if tests failed
+      if: steps.robot.outputs.exit_code != '0'
+      run: |
+        echo "❌ Robot Framework tests failed."
+        exit 1
